### ISSUE TITLE
BillboardViewModel initializer is internal

### ISSUE THREAD

**Issue by Dean151** [hiddevdploeg/Billboard#17]
Not sure of the use case that makes it internal only, but I'd rather have at least one public option to initialize one and keep it around in my own views

**Comment by appfrosch** [comment]
I agree and I guess, this is a bug. The `init` itself has to be made `public` explicitly in order to use `BillboardViewModel` when using the package in your app as a dependency–otherwise the default value of `internal` is assumed.

That's the error that you are seeing and that I also just ran into.

While this is being looked at, you can work around this by
1. cloning the repo
2. pulling the local package into Xcode
3. change `init` to `public init` in `BillboardViewModel`

This is what I did to make it work.

**Comment by appfrosch** [comment]
Hey @hiddevdploeg, 

thanks for the repo, I think it's a great idea and I hope this is going to be used by indies!

Have you considered enabling creating pull requests for this repo? This would be an easy fix even for somebody mid-level iOS developer like me 😀

**Comment by appfrosch** [comment]
I just answered myself (sorry, this is my first commit to open source...)–I had to fork and then create the pull request.
